/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerRestaurantsRouteImport } from './routes/manager.restaurants'
import { Route as ManagerMapRouteImport } from './routes/manager.map'
import { Route as ManagerEditIdRouteImport } from './routes/manager.edit.$id'
import { Route as ManagerChargeIdRouteImport } from './routes/manager.charge.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRestaurantsRoute = ManagerRestaurantsRouteImport.update({
  id: '/manager/restaurants',
  path: '/manager/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerMapRoute = ManagerMapRouteImport.update({
  id: '/manager/map',
  path: '/manager/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerEditIdRoute = ManagerEditIdRouteImport.update({
  id: '/manager/edit/$id',
  path: '/manager/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerChargeIdRoute = ManagerChargeIdRouteImport.update({
  id: '/manager/charge/$id',
  path: '/manager/charge/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager/map': typeof ManagerMapRoute
  '/manager/restaurants': typeof ManagerRestaurantsRoute
  '/manager/': typeof ManagerIndexRoute
  '/manager/charge/$id': typeof ManagerChargeIdRoute
  '/manager/edit/$id': typeof ManagerEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager/map': typeof ManagerMapRoute
  '/manager/restaurants': typeof ManagerRestaurantsRoute
  '/manager': typeof ManagerIndexRoute
  '/manager/charge/$id': typeof ManagerChargeIdRoute
  '/manager/edit/$id': typeof ManagerEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager/map': typeof ManagerMapRoute
  '/manager/restaurants': typeof ManagerRestaurantsRoute
  '/manager/': typeof ManagerIndexRoute
  '/manager/charge/$id': typeof ManagerChargeIdRoute
  '/manager/edit/$id': typeof ManagerEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager/map'
    | '/manager/restaurants'
    | '/manager/'
    | '/manager/charge/$id'
    | '/manager/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manager/map'
    | '/manager/restaurants'
    | '/manager'
    | '/manager/charge/$id'
    | '/manager/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/manager/map'
    | '/manager/restaurants'
    | '/manager/'
    | '/manager/charge/$id'
    | '/manager/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerMapRoute: typeof ManagerMapRoute
  ManagerRestaurantsRoute: typeof ManagerRestaurantsRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerChargeIdRoute: typeof ManagerChargeIdRoute
  ManagerEditIdRoute: typeof ManagerEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/restaurants': {
      id: '/manager/restaurants'
      path: '/manager/restaurants'
      fullPath: '/manager/restaurants'
      preLoaderRoute: typeof ManagerRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/map': {
      id: '/manager/map'
      path: '/manager/map'
      fullPath: '/manager/map'
      preLoaderRoute: typeof ManagerMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/edit/$id': {
      id: '/manager/edit/$id'
      path: '/manager/edit/$id'
      fullPath: '/manager/edit/$id'
      preLoaderRoute: typeof ManagerEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/charge/$id': {
      id: '/manager/charge/$id'
      path: '/manager/charge/$id'
      fullPath: '/manager/charge/$id'
      preLoaderRoute: typeof ManagerChargeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerMapRoute: ManagerMapRoute,
  ManagerRestaurantsRoute: ManagerRestaurantsRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerChargeIdRoute: ManagerChargeIdRoute,
  ManagerEditIdRoute: ManagerEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
